clinica_core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('', include('login_app.urls')),  #app de login
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('servicios/', views.servicios, name='servicios'),
    path('contacto/', views.contacto, name='contacto'),
]

main_app/models.py
from django.db import models

class Contactanos(models.Model):
    nombre = models.CharField(max_length=100)
    correo = models.EmailField(max_length=100)
    telefono = models.CharField(max_length=15)
    mensaje = models.TextField()
    fecha_envio = models.DateTimeField(auto_now_add=True)

templates/contactanos.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sonrisas Inclusivas - Contacto</title>
    <link rel="stylesheet" href="{% static 'css/contactanos.css' %}">
</head>
<body class="body">
    <header class="header-pagina">
        <h1>Clínica odontológica || Sonrisas Inclusivas<br><span class="palabras-importantes">Contacto</span></h1>
        <p></p>
    </header>
    <div class="contenedor-formulario">
        <div class="formulario-contacto">
            <h2>Contáctanos</h2>
            <form method="POST" action="{% url 'contacto' %}">
                {% csrf_token %}
                <div class="grupo-formulario">
                    <label for="id_nombre">Nombre:</label>
                    {{ form.nombre }}
                </div>
                <div class="grupo-formulario">
                    <label for="id_correo">Correo Electrónico:</label>
                    {{ form.correo }}
                </div>
                <div class="grupo-formulario">
                    <label for="id_telefono">Teléfono:</label>
                    {{ form.telefono }}
                </div>
                <div class="grupo-formulario">
                    <label for="id_mensaje">Mensaje:</label>
                    {{ form.mensaje }}
                </div>
                <button type="submit" class="boton-contacto">Enviar</button>
                {% if messages %}
                    <div class="alert alert-success" role="alert">
                        {% for message in messages %}
                            {{ message }}
                        {% endfor %}
                    </div>
                {% endif %}
            </form>                       
        </div>
    </div>
    <footer class="footer-pagina">
        <p>© 2024 Clínica odontológica <span class="palabras-importantes">Sonrisas Inclusivas</span> | Todos los derechos reservados.</p>
    </footer>
</body>
</html>
{% endblock %}

templates/index.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="es">
    <head>
        {% load static %}
        <title>Sonrisas Inclusivas - Inicio</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'css/index.css' %}">
    </head>
    <body>
        <header class="header">
            <h2>¡Tu sonrisa es nuestra prioridad!</h2>
            <p>Brindamos atención dental de calidad para toda la familia.</p>
            <a href="{% url 'contacto' %}">¡¡¡Agenda tu cita hoy!!!</a>
        </header>
        <div class="contenedor-info">
            <section class="informacion-home">
                <h2>Nuestra historia</h2>
                <p>Desde 2024, la clínica odontológica <strong>Sonrisas Inclusivas</strong> ha sido un faro de salud dental y bienestar en nuestra comunidad. Con una pasión inquebrantable por la excelencia y la inclusión, nos hemos comprometido a proporcionar atención dental de la más alta calidad en un ambiente acogedor y accesible para todos.</p>
                <img src="{% static 'img/historia.jpg' %}" alt="Historia de la clínica sonrisas inclusivas">
            </section class="informacion-home">
            <section class="informacion-home">
                <h2>Atención personalizada</h2>
                <p>En nuestra clínica, creemos firmemente en la importancia de la atención personalizada. Cada paciente es único, y nos dedicamos a asegurar que su experiencia sea lo más cómoda y satisfactoria posible. Desde el primer contacto hasta el final del tratamiento, nuestro equipo profesional está aquí para guiar y apoyar en cada paso del camino.</p>
                <img src="{% static 'img/atencion.jpg' %}" alt="Atención personalizada de la clínica sonrisas inclusivas">
            </section>
            <section class="informacion-home">
                <h2>Nuestro equipo</h2>
                <p>Nuestro equipo de expertos dentales está compuesto por profesionales altamente calificados y dedicados que están comprometidos con la excelencia en cada aspecto de su trabajo. Nos enorgullece mantenernos al día con las últimas tecnologías y técnicas en odontología, asegurando así los mejores resultados para nuestros pacientes.</p>
                <img src="{% static 'img/equipo.jpg' %}" alt="Equipo de trabajo de la clínica sonrisas inclusivas">
            </section>
        </div>
        <footer class="footer">
            <p>© 2024 Clínica Odontológica || Sonrisas Inclusivas S.A.S</p>
        </footer>
    </body>
</html>
{%endblock%}

templates/servicios.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="es">
    <head>
        <title>Servicios - Sonrisas Inclusivas</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'css/servicios.css' %}">
    </head>
    <body class="body">
        <header class="header-pagina">
            <h1>Clínica odontológica || Sonrisas Inclusivas<br><span class="palabras-importantes">Nuestros servicios</span></h1>
        </header>
        <section class="contenedor-servicios">
        <div class="servicio">
            <h2>Consulta odontológica</h2>
            <p>Visita al dentista para evaluar y cuidar de tu salud bucal. Durante esta visita, un odontólogo o higienista dental realizará una revisión completa de tu boca, dientes y encías.</p>
            <p class="precio">$50,000</p>
        </div>
        <div class="servicio">
            <h2>Blanqueamiento dental</h2>
            <p>Tratamiento estético que busca aclarar el tono o color de tus dientes para que luzcan más blancos y brillantes. Con el tiempo, los dientes pueden oscurecerse debido a factores como el consumo de alimentos y bebidas colorantes (café, té, vino tinto), el tabaco, algunos medicamentos o simplemente por el paso del tiempo.</p>
            <p class="precio">$200,000</p>
        </div>
        <div class="servicio">
            <h2>Ortodoncia</h2>
            <p>Ayuda a corregir la posición de los dientes y la mordida. Es decir, si tienes los dientes torcidos, apiñados o tienes problemas para morder correctamente, un ortodoncista puede ayudarte a solucionarlo.</p>
            <p class="precio">$3,000,000</p>
        </div>
        <div class="servicio">
            <h2>Implantes dentales</h2>
            <p>Es una solución moderna y duradera para reemplazar dientes perdidos. Son pequeños tornillos de titanio que se colocan en el hueso maxilar (mandíbula superior) o mandibular (mandíbula inferior) para servir como raíz de un diente artificial.</p>
            <p class="precio">$2,500,000 por diente</p>
        </div>
        <div class="servicio">
            <h2>Limpieza dental</h2>
            <p>Es un procedimiento esencial para mantener una buena salud bucal. Consiste en la eliminación profesional de la placa bacteriana y el sarro acumulados en los dientes y debajo de las encías.</p>
            <p class="precio">$80,000</p>
        </div>
            <div class="servicio">
                <h2>Endodoncia</h2>
                <p>Es un tratamiento dental que se realiza cuando la pulpa de un diente está infectada o dañada. La pulpa es la parte interna del diente que contiene nervios y vasos sanguíneos.</p>
                <p class="precio">$400,000</p>
            </div>
        </section>
    <footer class="footer-pagina">
        <p>© 2024 Clínica odontológica <span class="palabras-importantes">Sonrisas Inclusivas</span> | Todos los derechos reservados.</p>
    </footer>
</html>
{% endblock %}